export const auditCategoryLabels: Record<string, string> = {
  auth: "Авторизация",
  security: "Безопасность",
  clients: "Клиенты",
  services: "Услуги",
  payments: "Платежи",
  expenses: "Расходы",
  expense_category: "Статьи расходов",
  schedule: "Расписание",
  users: "Пользователи",
  recurring_tasks: "Регулярные задачи",
  courses: "Курсы",
  course_enrollments: "Назначения курсов",
  course_progress: "Прогресс по курсам",
};

export const auditActionLabels: Record<string, string> = {
  invite_created: "Создано приглашение",
  superuser_bootstrap_invite_available: "Доступно bootstrap-приглашение суперпользователя",
  user_registered: "Пользователь зарегистрирован",
  login_succeeded: "Вход выполнен",
  logout_succeeded: "Выход из сессии",
  logout_all_succeeded: "Выход из всех сессий",
  session_revoked: "Сессия завершена",
  password_changed: "Пароль изменен",
  password_reset_link_created: "Создана ссылка на восстановление пароля",
  password_reset_completed: "Пароль восстановлен",
  two_factor_removed: "2FA отключена",
  recovery_codes_regenerated: "Коды восстановления обновлены",
  client_created: "Клиент создан",
  client_updated: "Клиент обновлен",
  client_vacations_updated: "Периоды отсутствия клиента обновлены",
  client_deleted: "Клиент удален",
  client_portal_link_created: "Создана ссылка на кабинет клиента",
  client_portal_pin_reset: "PIN кабинета клиента сброшен",
  lead_closed: "Лид закрыт",
  lead_reopened: "Лид возвращен в работу",
  service_created: "Услуга создана",
  service_updated: "Услуга обновлена",
  service_deleted: "Услуга удалена",
  service_price_updated: "Цена услуги изменена",
  payment_created: "Платеж создан",
  payment_updated: "Платеж изменен",
  payment_deleted: "Платеж удален",
  expense_created: "Расход создан",
  expense_updated: "Расход изменен",
  expense_deleted: "Расход удален",
  expense_category_created: "Статья расхода создана",
  expense_category_deleted: "Статья расхода удалена",
  client_source_created: "Источник клиента создан",
  client_source_deleted: "Источник клиента удален",
  appointment_created: "Встреча создана",
  recurring_appointment_created: "Повторяющаяся встреча создана",
  appointment_updated: "Встреча обновлена",
  recurring_appointment_detached_and_updated: "Повторяющаяся встреча изменена отдельно",
  appointment_deleted: "Встреча удалена",
  recurring_appointments_rescheduled: "Вся серия перенесена",
  recurring_appointments_split_and_rescheduled: "Серия разделена и перенесена",
  appointments_deleted_this_and_following: "Удалены эта и следующие встречи",
  appointments_deleted_all: "Удалена вся серия",
  appointments_deleted_selected_weekday_this_and_following: "Удалены выбранный день и следующие",
  appointments_deleted_selected_weekday_all: "Удален выбранный день серии",
  user_updated: "Пользователь обновлен",
  user_availability_updated: "Доступность пользователя обновлена",
  recurring_task_rule_updated: "Правило регулярной задачи обновлено",
  custom_task_created: "Пользовательская задача создана",
  task_completed: "Регулярная задача завершена",
  task_cancelled: "Регулярная задача отменена",
  task_delayed: "Регулярная задача отложена",
  course_created: "Курс создан",
  course_updated: "Курс обновлен",
  course_deleted: "Курс удален",
  course_enrollment_created: "Курс назначен клиенту",
  course_enrollment_deleted: "Курс снят с клиента",
  course_theme_unlocked: "Тема курса открыта",
  course_theme_started: "Работа над темой начата",
  course_theme_sent_to_homework: "Тема отправлена на домашнюю работу",
  course_theme_homework_passed: "Домашняя работа принята",
  course_theme_returned_to_progress: "Тема возвращена в работу",
};

export function formatAuditLabel(value: string, labels: Record<string, string>) {
  return labels[value] ?? value;
}
