import type { TourProps } from "antd";

type OnboardingAudience = "all" | "admin" | "superuser" | "stats";

export type OnboardingStepDefinition = {
  id: string;
  path: string;
  targetId: string;
  audience?: OnboardingAudience;
} & Pick<NonNullable<TourProps["steps"]>[number], "title" | "description" | "placement">;

export const onboardingSteps: OnboardingStepDefinition[] = [
  {
    id: "welcome",
    path: "/",
    targetId: "shell-brand",
    placement: "right",
    title: "Общая структура CRM",
    description: "Этот гид показывает основные разделы CRM и порядок работы с ними. Переход между шагами выполняется кнопками внизу.",
  },
  {
    id: "navigation",
    path: "/",
    targetId: "shell-navigation",
    placement: "right",
    title: "Навигация",
    description: "В этом меню находятся рабочие страницы CRM, аналитика и справочники. Состав меню зависит от роли пользователя.",
  },
  {
    id: "dashboard",
    path: "/",
    targetId: "dashboard-content",
    placement: "top",
    title: "Страница обзора",
    description: "Страница обзора показывает ключевые показатели по работе CRM. Состав карточек зависит от роли пользователя.",
  },
  {
    id: "dashboard-debtors",
    path: "/",
    targetId: "dashboard-debtors",
    placement: "top",
    title: "Блок должников",
    description: "Этот блок показывает клиентов с отрицательным балансом. Из него можно открыть историю клиента и выгрузить список должников.",
    audience: "admin",
  },
  {
    id: "schedule-navigation",
    path: "/schedule",
    targetId: "schedule-header-actions",
    placement: "bottom",
    title: "Страница расписания",
    description: "В шапке страницы находятся переход между неделями и возврат к текущей неделе.",
  },
  {
    id: "schedule-create",
    path: "/schedule",
    targetId: "schedule-header-actions",
    placement: "bottom",
    title: "Создание записи",
    description: "Для администраторов в шапке страницы доступно создание новой записи.",
    audience: "admin",
  },
  {
    id: "schedule-toolbar",
    path: "/schedule",
    targetId: "schedule-toolbar",
    placement: "bottom",
    title: "Фильтры расписания",
    description: "В этой панели администратор может выбрать преподавателя, быстро перейти к собственному расписанию и сбросить фильтр.",
    audience: "admin",
  },
  {
    id: "schedule-calendar",
    path: "/schedule",
    targetId: "schedule-calendar",
    placement: "top",
    title: "Календарь записей",
    description: "Календарь показывает рабочую неделю, занятые интервалы, статусы записей и нерабочее время преподавателей. Из календаря можно открыть детали записи.",
  },
  {
    id: "clients",
    path: "/clients",
    targetId: "clients-page-content",
    placement: "top",
    title: "Страница клиентов",
    description: "Страница клиентов содержит поиск, список клиентов, баланс, контакты, историю посещений и источник клиента.",
    audience: "admin",
  },
  {
    id: "clients-actions",
    path: "/clients",
    targetId: "clients-actions",
    placement: "bottom",
    title: "Создание и изменение клиента",
    description: "Кнопка в шапке открывает создание клиента. В строке клиента доступны просмотр истории, изменение и удаление.",
    audience: "admin",
  },
  {
    id: "services-list",
    path: "/services",
    targetId: "services-page-content",
    placement: "top",
    title: "Страница услуг",
    description: "Здесь хранится список услуг, их описание и текущая цена. Эти данные используются в расписании, платежах и аналитике.",
    audience: "admin",
  },
  {
    id: "services-actions",
    path: "/services",
    targetId: "services-actions",
    placement: "bottom",
    title: "Создание услуги и изменение цены",
    description: "Кнопка в шапке создает новую услугу. Кнопка со значком валюты в строке открывает изменение цены существующей услуги.",
    audience: "admin",
  },
  {
    id: "payments-filters",
    path: "/payments",
    targetId: "payments-filters",
    placement: "bottom",
    title: "Фильтры платежей",
    description: "На странице платежей доступны поиск по клиенту, услуге и описанию, а также фильтр по периоду.",
    audience: "admin",
  },
  {
    id: "payments-summary",
    path: "/payments",
    targetId: "payments-summary",
    placement: "top",
    title: "Список платежей",
    description: "Сводные карточки показывают сумму, количество и дату последнего платежа. Ниже находится таблица всех платежных операций.",
    audience: "admin",
  },
  {
    id: "payments-create",
    path: "/payments",
    targetId: "payments-actions",
    placement: "left",
    title: "Создание платежа",
    description: "Создание платежа выполняется из кнопки в шапке. Платеж можно связать с клиентом и услугой, а при необходимости быстро создать нового клиента.",
    audience: "admin",
  },
  {
    id: "expenses-filters",
    path: "/expenses",
    targetId: "expenses-filters",
    placement: "bottom",
    title: "Фильтры расходов",
    description: "На странице расходов доступны поиск по описанию и фильтр по периоду.",
    audience: "admin",
  },
  {
    id: "expenses-summary",
    path: "/expenses",
    targetId: "expenses-summary",
    placement: "top",
    title: "Список расходов",
    description: "Сводные карточки показывают сумму, количество и дату последнего расхода. Ниже находится таблица расходных операций.",
    audience: "admin",
  },
  {
    id: "expenses-create",
    path: "/expenses",
    targetId: "expenses-actions",
    placement: "left",
    title: "Создание расхода",
    description: "Создание расхода выполняется из кнопки в шапке. В форме можно выбрать статью расходов или создать новую категорию.",
    audience: "admin",
  },
  {
    id: "expense-categories",
    path: "/expense-categories",
    targetId: "expense-categories-page-content",
    placement: "top",
    title: "Справочник статей расходов",
    description: "Этот справочник используется для ведения категорий расходов. Категории из него доступны при создании и анализе расходов.",
    audience: "admin",
  },
  {
    id: "client-sources",
    path: "/client-sources",
    targetId: "client-sources-page-content",
    placement: "top",
    title: "Справочник источников клиентов",
    description: "Этот справочник используется для учета каналов привлечения клиентов. Источники применяются в карточке клиента и в клиентской аналитике.",
    audience: "admin",
  },
  {
    id: "revenue-filters",
    path: "/revenue",
    targetId: "revenue-filters",
    placement: "bottom",
    title: "Фильтры аналитики выручки",
    description: "На странице выручки выбираются период и группировка. Эти настройки влияют на сводку, графики и таблицы.",
    audience: "stats",
  },
  {
    id: "revenue-blocks",
    path: "/revenue",
    targetId: "revenue-main-blocks",
    placement: "top",
    title: "Блоки аналитики выручки",
    description: "Страница показывает фактическую и плановую выручку, чистую прибыль, структуру по услугам, а также таблицы по преподавателям, клиентам и периодам.",
    audience: "stats",
  },
  {
    id: "price-changes-filters",
    path: "/price-changes",
    targetId: "price-changes-filters",
    placement: "bottom",
    title: "Фильтры аналитики изменения цен",
    description: "На этой странице выбираются период изменения цены и окно сравнения до и после изменения.",
    audience: "stats",
  },
  {
    id: "price-changes-table",
    path: "/price-changes",
    targetId: "price-changes-main-table",
    placement: "top",
    title: "Результаты изменения цен",
    description: "Основная таблица показывает старую и новую цену, изменение спроса, изменение выручки и дополнительные показатели по каждой услуге.",
    audience: "stats",
  },
  {
    id: "appointments-stats-summary",
    path: "/appointments-stats",
    targetId: "appointments-stats-summary",
    placement: "top",
    title: "Сводка по записям",
    description: "Сводка показывает количество записей по статусам, рабочее и занятое время преподавателей, загрузку и выручку по занятиям.",
    audience: "stats",
  },
  {
    id: "appointments-stats-blocks",
    path: "/appointments-stats",
    targetId: "appointments-stats-main-blocks",
    placement: "top",
    title: "Разделы аналитики записей",
    description: "Ниже находятся графики статусов и загрузки, таблица по преподавателям, анализ часов, список клиентов со сгоревшими записями и дневная детализация.",
    audience: "stats",
  },
  {
    id: "clients-stats-summary",
    path: "/clients-stats",
    targetId: "clients-stats-summary",
    placement: "top",
    title: "Сводка по клиентам",
    description: "Сводка показывает количество клиентов, удержание, новых и потерянных клиентов, риск ухода, LTV, сегменты и задолженность.",
    audience: "stats",
  },
  {
    id: "clients-stats-blocks",
    path: "/clients-stats",
    targetId: "clients-stats-main-blocks",
    placement: "top",
    title: "Разделы клиентской аналитики",
    description: "Ниже находятся блоки по источникам, топ клиентам по LTV, сегментам, RFM-анализу и подробная таблица по источникам.",
    audience: "stats",
  },
  {
    id: "payments-stats-summary",
    path: "/payments-stats",
    targetId: "payments-stats-summary",
    placement: "top",
    title: "Сводка по платежам и долгу",
    description: "Сводка показывает неоплаченные записи, число должников, общий долг и задержки оплаты.",
    audience: "stats",
  },
  {
    id: "payments-stats-blocks",
    path: "/payments-stats",
    targetId: "payments-stats-main-blocks",
    placement: "top",
    title: "Разделы платежной аналитики",
    description: "Ниже находятся структура долга по услугам, крупнейшие должники, баланс по клиентам и отдельные срезы по преподавателям и услугам.",
    audience: "stats",
  },
  {
    id: "expenses-stats-summary",
    path: "/expenses-dashboard",
    targetId: "expenses-stats-summary",
    placement: "top",
    title: "Сводка по расходам",
    description: "Сводка показывает сумму расходов, долю расходов от выручки, количество операций и крупнейшие категории.",
    audience: "stats",
  },
  {
    id: "expenses-stats-blocks",
    path: "/expenses-dashboard",
    targetId: "expenses-stats-main-blocks",
    placement: "top",
    title: "Разделы аналитики расходов",
    description: "Ниже находятся график расходов, структура по категориям, динамика по периодам и таблица категорий.",
    audience: "stats",
  },
  {
    id: "users",
    path: "/users",
    targetId: "users-page-content",
    placement: "top",
    title: "Страница пользователей",
    description: "Страница пользователей доступна администраторам. Она показывает список пользователей системы и их роли.",
    audience: "admin",
  },
  {
    id: "users-invite",
    path: "/users",
    targetId: "users-actions",
    placement: "bottom",
    title: "Приглашение пользователя",
    description: "Кнопка в шапке создает приглашение с ролью и, при необходимости, с привязкой к email. После создания ссылку можно скопировать и отправить сотруднику.",
    audience: "admin",
  },
  {
    id: "audit",
    path: "/audit",
    targetId: "audit-page-content",
    placement: "top",
    title: "Журнал аудита",
    description: "Журнал аудита доступен суперпользователю. Здесь можно искать действия пользователей и изменения данных по системе.",
    audience: "superuser",
  },
  {
    id: "profile",
    path: "/profile",
    targetId: "profile-account-card",
    placement: "bottom",
    title: "Профиль пользователя",
    description: "В профиле находятся данные аккаунта, настройки безопасности, рабочий график, отпуска и активные сессии.",
  },
  {
    id: "profile-availability",
    path: "/profile",
    targetId: "profile-availability",
    placement: "top",
    title: "Рабочий график",
    description: "В этом блоке задаются рабочие часы и отпуска. Эти настройки используются в расписании и в аналитике загрузки.",
  },
  {
    id: "profile-security",
    path: "/profile",
    targetId: "profile-security",
    placement: "top",
    title: "Безопасность и сессии",
    description: "Здесь находятся смена пароля, двухфакторная защита, коды восстановления и список активных сессий.",
  },
  {
    id: "profile-onboarding",
    path: "/profile",
    targetId: "profile-onboarding-reset",
    placement: "bottom",
    title: "Повторный запуск гида",
    description: "Если нужно пройти обучение заново, используйте этот блок для сброса прогресса гида.",
  },
];

export function canAccessOnboardingStep(
  step: OnboardingStepDefinition,
  user?: { isAdmin?: boolean; isSuperuser?: boolean } | null,
) {
  switch (step.audience) {
    case "superuser":
      return Boolean(user?.isSuperuser);
    case "admin":
      return Boolean(user?.isAdmin);
    case "stats":
      return Boolean(user?.isAdmin || user?.isSuperuser);
    default:
      return true;
  }
}
